"""Migrations with the right columns.

Revision ID: 88a372678e19
Revises: 
Create Date: 2025-06-18 15:34:41.175526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a372678e19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('monster_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('element_type', sa.String(), nullable=False),
    sa.Column('base_stats', sa.JSON(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Integer(), nullable=True),
    sa.Column('player2_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('battle_inventory', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name=op.f('fk_battles_player1_id_players')),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name=op.f('fk_battles_player2_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('achievement_id', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_player_achievements_achievement_id_achievements')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_achievements_player_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('current_stats', sa.JSON(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_monsters_player_id_players')),
    sa.ForeignKeyConstraint(['species_id'], ['monster_species.id'], name=op.f('fk_player_monsters_species_id_monster_species')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_playerID', sa.Integer(), nullable=True),
    sa.Column('to_playerID', sa.Integer(), nullable=True),
    sa.Column('offered_monsters', sa.JSON(), nullable=True),
    sa.Column('requested_monsters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['from_playerID'], ['players.id'], name=op.f('fk_trades_from_playerID_players')),
    sa.ForeignKeyConstraint(['to_playerID'], ['players.id'], name=op.f('fk_trades_to_playerID_players')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('player_monsters')
    op.drop_table('player_achievements')
    op.drop_table('battles')
    op.drop_table('players')
    op.drop_table('monster_species')
    op.drop_table('achievements')
    # ### end Alembic commands ###
